# Generated by Django 6.0.6 on 2026-06-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_capacitaciones_usuario_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='id_estados_civiles',
            field=models.ForeignKey(blank=True, db_column='id_estados_civiles', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estadocivil'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='id_generos',
            field=models.ForeignKey(blank=True, db_column='id_generos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.genero'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='id_tipos_documento',
            field=models.ForeignKey(blank=True, db_column='id_tipos_documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipodocumento'),
        ),
    ]
